name: quiz

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: date 1
              run: date
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: date 2
              run: date
    job3:
        name: third job
        runs-on: macos-latest
        steps:
            - name: date 3
              run: date
    job4:
        name: fourth job
        runs-on: ubuntu-latest
        needs: [job1, job2, job3]
        steps:
            - name: date 4
              run: date
